# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bd9d36d9a4ef4e53435437320e83359a32cf14091c20db10d92eb128c7c8eef4a208c4f68ec82b09bdafbd59dd43d95b6b0ea6c11dc66709d7acf7cd2fef394

test:
  secret_key_base: 8abbd7489883df66968e37e76f24e0478f9d33d1a1829d91b53839e4af882029f5f2ce71ebff57fa36149cb4cf824c8293d6860b9c962aaeb791bee681dbc772

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
